using static System.Net.WebRequestMethods;

namespace AspNetMvcBlog.Models
{
    public class DatabaseContent
    {
        public List<BlogText> _Blogs { get; set; }
        public List<Catagory> _Catagories { get; set; }
        public DatabaseContent()
        {
            _Blogs = new List<BlogText>()
            {
                new BlogText(){Id = 1, Title = "Yapay Zeka ve Etik: Sorunlar ve Çözümler", Content = "Günümüzde yapay zeka (YZ) teknolojisi, hayatımızın birçok alanında hızla yaygınlaşmaktadır. Özerk sürüş teknolojileri, tıbbi teşhis ve tedavi, kişisel asistanlar ve daha birçok uygulama yapay zeka algoritmaları tarafından desteklenmektedir. Ancak, yapay zekanın gelişimi ve yaygın kullanımı beraberinde bazı etik ve sorunları getiriyor. Bu blog yazısında, yapay zeka ve etik arasındaki ilişkiyi inceleyerek, ortaya çıkan sorunlara odaklanacağız ve bu sorunları çözmek için neler yapabileceğimizi tartışacağız.\r\n\r\n1. Veri Gizliliği ve Mahremiyet:\r\nYapay zeka uygulamaları, büyük miktarda veri toplama ve analiz etme yeteneğine sahiptir. Bu veriler, kullanıcıların özel bilgilerini içerebilir ve kötü amaçlı kişilerin eline geçtiğinde tehlikeli sonuçlara yol açabilir. Bu nedenle, veri gizliliği ve mahremiyeti, yapay zeka teknolojilerinin geliştirilmesinde ve kullanılmasında ele alınması gereken önemli bir etik meseledir.\r\n\r\n2. Algoritma Yanlılığı ve Adalet:\r\nYapay zeka algoritmaları, eğitim verilerine dayanarak kararlar verirler. Ancak, eğitim verilerindeki yanlılık, yapay zekanın da yanlı sonuçlar üretmesine neden olabilir. Örneğin, yüz tanıma algoritmaları bazı etnik grupları yanlış tanıyabilir veya cezai algoritmalar bazı kişilere haksız yere daha sert cezalar verebilir. Algoritma yanlılığını azaltmak ve adil yapay zeka sistemleri geliştirmek için adımlar atılmalıdır.\r\n\r\n3. İşsizlik ve İş Gücü Dönüşümü:\r\nYapay zeka ve otomasyon teknolojileri, birçok sektörde işleri otomatikleştirme potansiyeline sahiptir. Bu durum, bazı işlerin kaybolmasına ve iş gücü dönüşümünün gerekliliğine yol açabilir. Yapay zekanın ekonomik ve sosyal etkilerini dikkate alarak, iş gücü dönüşümü için uygun politikaların geliştirilmesi önemlidir.\r\n\r\n4. Karar Alma ve Sorumluluk:\r\nYapay zeka uygulamaları, önemli kararlar alabilir ve insanların hayatlarını etkileyebilir. Özerk sürüş teknolojilerinde olduğu gibi, araçların trafik kazalarında karar verme sorumluluğu tartışmalıdır. Bu tür durumlarda, yapay zekanın algoritma temelli kararları kimin sorumlu olduğu konusunda netlik sağlanmalıdır.\r\n\r\n5. İnsanlık ve Yapay Zeka İlişkisi:\r\nYapay zeka teknolojisinin gelişmesi, insanların teknolojiye olan bağımlılığını artırabilir ve sosyal ilişkileri etkileyebilir. Ayrıca, bazı yapay zeka uygulamaları, insan benzeri etkileşimler ve duygusal tepkiler sunarak insanlarla daha kişisel bir ilişki kurmayı amaçlayabilir. Bu bağlamda, insanlık ve yapay zeka arasındaki etik boyutlar üzerine düşünmek önemlidir.", Author = "ChatGPT Reis", CatagoryId=1, Comments={}, Tag="Teknoloji", imageUrl="~/images/news/f1.jpg" },



				new BlogText(){Id = 2, Title = "Bitkilerin Gizemli Dünyası: Canlılar Krallığındaki Sessiz Kahramanlar", Content = "Dünya üzerindeki canlıların çeşitliliği içinde bitkiler, kendine özgü ve gizemli bir dünya sunarlar. Yeşillikleriyle doğanın en önemli yapı taşlarından biri olan bitkiler, pek çok açıdan hayati öneme sahiptir. Bu yazıda, bitkilerin dünyasına mercek tutarak onların yaşamları, önemi ve bize sağladığı faydaları inceleyeceğiz.\r\n\r\n1. Bitkilerin Yaşam Döngüsü ve Çeşitliliği:\r\nBitkilerin yaşam döngüsü, tohumdan büyüyerek yetişkin bitkiye dönüşüm ve üreme aşamalarını içerir. Bitkiler, dünya üzerindeki çeşitlilikleriyle büyüleyici bir manzara sunarlar. Çiçek açan bitkiler, çalılar, ağaçlar, otsu bitkiler ve sarmaşıklar gibi birçok farklı türü vardır. Bu zengin çeşitlilik, bitkilerin hayatta kalabilmek için doğal seçilime nasıl uyum sağladığını gösterir.\r\n\r\n2. Fotosentez ve Atmosferin Düzenlenmesi:\r\nBitkiler, fotosentez yoluyla güneş enerjisini kullanarak karbondioksiti (CO2) ve suyu oksijene ve organik bileşiklere dönüştürürler. Fotosentez sayesinde bitkiler, atmosferdeki CO2 seviyelerini düşürerek gezegenimizin yaşam için uygun sıcaklık ve koşullara sahip olmasına katkıda bulunurlar.\r\n\r\n3. Besin Zinciri ve Ekosistemlerin Dengesi:\r\nBitkiler, besin zincirinin temel halkasını oluştururlar. Bitkiler, fotosentez yoluyla ürettikleri organik bileşikleri diğer canlı organizmalar için besin olarak sunarlar. Bu şekilde, bitkiler, ekosistemlerde besin zincirini başlatır ve ekosistemlerin dengeli bir şekilde işlemesine katkı sağlarlar.\r\n\r\n4. İlaç ve Gıda Kaynağı Olarak Bitkiler:\r\nBitkiler, geleneksel tıpta binlerce yıldır kullanılan doğal ilaçlar ve şifalı bitkilerin kaynağıdır. Modern tıpta da pek çok ilaç bitkisel kökenli maddelerden elde edilir. Ayrıca, besinlerin büyük bir kısmını bitkiler sağlar. Sebzeler, meyveler, tahıllar ve baklagiller gibi temel besin gruplarının çoğu bitkisel kökenlidir.", Author = "ChatGPT Reis", CatagoryId=2, Comments={}, Tag="Bitkiler", imageUrl="\"https://cdn.evrimagaci.org/VXqhBWliS2WrFSeAAk0xuOmK5QY=/evrimagaci.org%2Fpublic%2Fcontent_media%2Fd53a0d7e1d52ff4e0a0c75e08074d01c.jpg\"" },


				  new BlogText(){Id = 3, Title = "Şehrin Kalbi: Sokaklarından Kültürüne, Şehirlerin Sırları", Content = "Şehirler, insanların tarih boyunca yaşamaya başladığı ve uygarlıkların doğduğu yerlerdir. İnsanların bir araya gelerek sosyal, ekonomik ve kültürel faaliyetlerde bulunduğu şehirler, çeşitlilikleri ve zenginlikleriyle dikkat çekerler. Bu yazıda, şehirlerin sokaklarından kültürlerine, mimarisinden insanlarına kadar çeşitli yönlerini keşfederek şehirlerin sırlarını inceleyeceğiz.\r\n\r\n1. Tarihi Sokaklar ve Mirasları:\r\nŞehirlerin tarihi sokakları, geçmişe dair ipuçları taşır. Eski binalar, anıtlar, sokak taşları ve eski meydanlar, şehrin tarihini anlamak için önemli kaynaklardır. Tarihi sokaklar, mimari mirasın korunması ve kültürel kimliğin devamı için değerlidir.\r\n\r\n2. Çeşitlilik ve Kültürel Zenginlik:\r\nŞehirler, farklı kültürlerin bir arada yaşadığı merkezlerdir. Bu çeşitlilik, şehirlerin yemek kültüründen sanata, dil ve geleneklere kadar farklılıklar yaratır. Şehirler, farklı kültürlerin etkileşimine olanak tanır ve böylece toplumsal çeşitlilik ve zenginlik oluşturur.\r\n\r\n3. Şehrin Ritmi ve Hızı:\r\nŞehirler, sürekli hareket halinde olan yerlerdir. İnsanlar, işe gidip gelir, alışveriş yapar, sosyalleşir ve kültürel etkinliklere katılır. Şehrin ritmi, zamanın hızlı akışını simgelerken, her anında farklı bir yaşamın kapısını aralar.\r\n\r\n4. Şehir Planlaması ve Mimarisi:\r\nŞehir planlaması ve mimarisi, bir şehrin karakterini belirleyen önemli unsurlardır. Caddelerin düzeni, binaların mimarisi ve yeşil alanların varlığı, bir şehrin estetik ve fonksiyonel özelliklerini yansıtır. Şehirlerin planlaması, sürdürülebilirlik ve insanların yaşam kalitesi açısından büyük önem taşır.\r\n\r\n5. Şehirdeki Toplumsal ve Ekonomik Dinamikler:\r\nŞehirler, ekonomik ve sosyal faaliyetlerin merkezleridir. Ticaret, endüstri, eğitim ve sağlık gibi birçok alanda şehirlerde yoğun etkinlikler görülür. Şehirler, iş imkanları ve toplumsal olanaklar açısından cazip noktalardır.\r\n\r\n6. Şehir ve Çevre:\r\nŞehirler, doğal çevre ile etkileşim içindedir. Yeşil alanların varlığı, hava kirliliği ve trafik yoğunluğu gibi çevresel faktörler, şehirlerin yaşanabilirliğini etkiler. Şehirlerin sürdürülebilirlik adına çevre dostu politikalar uygulaması önemlidir.\r\n\r\nŞehirler, insanların sosyal, ekonomik ve kültürel yaşamını şekillendiren yaşam alanlarıdır. Sokaklarından kültürel zenginliklerine kadar birçok sırrı barındıran şehirler, insanlık tarihinde önemli bir rol oynamıştır. Günümüzde de şehirler, sosyal etkileşimlerin merkezi ve ilerlemenin motorudur. Şehirlerin değerini anlamak ve gelecek nesiller için yaşanabilir ve sürdürülebilir şehirler oluşturmak, insanlığın ortak sorumluluğudur.", Author = "ChatGPT Reis", CatagoryId=3, Comments={}, Tag="Şehirler ve Medeniyet", imageUrl="\"https://cdn.evrimagaci.org/VXqhBWliS2WrFSeAAk0xuOmK5QY=/evrimagaci.org%2Fpublic%2Fcontent_media%2Fd53a0d7e1d52ff4e0a0c75e08074d01c.jpg\"" }


            };
            _Catagories = new List<Catagory>()
            {
                new Catagory(){Id = 1, CatagoryName ="Teknoloji"},
                 new Catagory(){Id = 2, CatagoryName ="Bitkiler"},
                  new Catagory(){Id = 3, CatagoryName ="Şehirler ve Medeniyet"}
            };
        }
    }
}
